# -*- coding: utf-8 -*-
"""Assign2_533444_Freta Yordinia Laura_Klasifikasi MNIST dengan ANN + Regularisasi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bqrg9_HK9A4eK6-sMsHhRbAgXEi9zPEt

# Assignment 2: Classify MNIST + Regularization

Freta Yordinia Laura   
24/533444/PA/22576

## Load Data
"""

import numpy as np
import matplotlib.pyplot as plt
import keras
import tensorflow as tf
from keras.datasets import mnist
from keras.models import Sequential, load_model
from keras.layers import Flatten, Dense

keras.utils.set_random_seed(42)
tf.config.experimental.enable_op_determinism()

(X_train, y_train), (X_test, y_test) = mnist.load_data()

X_train = X_train.reshape(-1, 28,28,1)
X_test = X_test.reshape(-1, 28,28,1)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255
y_train = keras.utils.to_categorical(y_train, 10)
y_test = keras.utils.to_categorical(y_test, 10)

print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

"""## Define and Compile Model"""

keras.utils.set_random_seed(42)
model1 = Sequential()
model1.add(Flatten())
model1.add(Dense(64, activation='relu'))
model1.add(Dense(10, activation='softmax'))

model1.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['acc'])

"""## Fit Model"""

history1 = model1.fit(X_train, y_train, epochs=10, batch_size=100, validation_data=(X_test, y_test))
model1.save('my_model1.h5')
model1.evaluate(X_test, y_test)
model1.summary()

epochs = range(10)
loss1 = history1.history['loss']
val_loss1 = history1.history['val_loss']
plt.plot(epochs, loss1, 'r', label='training loss ANN')
plt.plot(epochs, val_loss1, 'b', label='validation loss ANN')
plt.xlabel('epoch'); plt.ylabel('loss'); plt.title('Baseline ANN')
plt.legend(); plt.show()

# Tampilkan beberapa contoh citra
fig, axes = plt.subplots(2, 10, figsize=(12, 3))
for i, ax in enumerate(axes.flat):
    ax.imshow(X_train[i].reshape(28, 28), cmap='gray')
    ax.set_title(f'label = {np.argmax(y_train[i])}', fontsize=8)
    ax.axis('off')
plt.tight_layout(); plt.show()

"""## Load Model dan Prediction"""

model_simpan = load_model('my_model1.h5')
pred = model_simpan.predict(X_test)
print('label actual:', np.argmax(y_test[30]))
print('label prediction:', np.argmax(pred[30]))

"""# Eksperimen

## L1 Regularization (Rate = 0.0001)
"""

from keras import regularizers
keras.utils.set_random_seed(42)
model2 = Sequential()
model2.add(Flatten())
model2.add(Dense(64,activation='relu',kernel_regularizer=regularizers.l1(0.0001)))
model2.add(Dense(10,activation='softmax'))

model2.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['acc'])
history2 = model2.fit(X_train,y_train,epochs=10,batch_size=100,validation_data=(X_test,y_test))
model2.summary()
model2.evaluate(X_test,y_test)

loss2 = history2.history['loss']
val_loss2 = history2.history['val_loss']
plt.plot(range(10),loss2,'r',label='training loss L1')
plt.plot(range(10),val_loss2,'b',label='validation loss L1')
plt.legend()
plt.show()

"""## L2 Regularization (Rate = 0.001)"""

keras.utils.set_random_seed(42)
model3 = Sequential()
model3.add(Flatten())
model3.add(Dense(64,activation='relu',kernel_regularizer=regularizers.l2(0.001)))
model3.add(Dense(10,activation='softmax'))

model3.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['acc'])
history3 = model3.fit(X_train,y_train,epochs=10,batch_size=100,validation_data=(X_test,y_test))
model3.summary()
model3.evaluate(X_test,y_test)

loss3 = history3.history['loss']
val_loss3 = history3.history['val_loss']
plt.plot(range(10),loss3,'r',label='training loss L2')
plt.plot(range(10),val_loss3,'b',label='validation loss L2')
plt.legend()
plt.show()

"""## Dropout (Rate = 0.3)"""

from keras.layers import Dropout
keras.utils.set_random_seed(42)
model4 = Sequential()
model4.add(Flatten())
model4.add(Dense(64,activation='relu'))
model4.add(Dropout(0.3))
model4.add(Dense(10,activation='softmax'))

model4.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['acc'])
history4 = model4.fit(X_train,y_train,epochs=10,batch_size=100,validation_data=(X_test,y_test))
model4.summary()
model4.evaluate(X_test,y_test)

loss4 = history4.history['loss']
val_loss4 = history4.history['val_loss']
plt.plot(range(10),loss4,'r',label='training loss Dropout')
plt.plot(range(10),val_loss4,'b',label='validation loss Dropout')
plt.legend()
plt.show()

"""## Early Stopping"""

from keras.callbacks import EarlyStopping

es = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)
keras.utils.set_random_seed(42)
model5 = Sequential()
model5.add(Flatten())
model5.add(Dense(64,activation='relu'))
model5.add(Dense(10,activation='softmax'))

model5.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['acc'])
history5 = model5.fit(X_train,y_train,epochs=50,batch_size=100,validation_data=(X_test,y_test),callbacks=[es])
model5.summary()
model5.evaluate(X_test,y_test)

loss5 = history5.history['loss']
val_loss5 = history5.history['val_loss']
epochs5 = range(len(loss5))
plt.plot(epochs5,loss5,'r',label='training loss Early Stopping')
plt.plot(epochs5,val_loss5,'b',label='validation loss Early Stopping')
plt.legend()
plt.show()
print('berhenti di epoch', len(loss5))

"""## L1 Regularization + Dropout"""

keras.utils.set_random_seed(42)
model6 = Sequential()
model6.add(Flatten())
model6.add(Dense(64,activation='relu',kernel_regularizer=regularizers.l1(0.0001)))
model6.add(Dropout(0.3))
model6.add(Dense(10,activation='softmax'))

model6.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['acc'])
history6 = model6.fit(X_train,y_train,epochs=10,batch_size=100,validation_data=(X_test,y_test))
model6.summary()
model6.evaluate(X_test,y_test)

loss6 = history6.history['loss']
val_loss6 = history6.history['val_loss']
plt.plot(range(10),loss6,'r',label='training loss L1+Dropout')
plt.plot(range(10),val_loss6,'b',label='validation loss L1+Dropout')
plt.legend()
plt.show()

"""# Perbandingan Semua Model"""

models = [model1, model2, model3, model4, model5, model6]
names = ['Baseline', 'L1', 'L2', 'Dropout', 'Early Stopping', 'L1+Dropout']

for i in range(6):
    loss, acc = models[i].evaluate(X_test, y_test, verbose=0)
    print(names[i], '-> acc:', round(acc,4), ' loss:', round(loss,4))

histories = [history1, history2, history3, history4, history5, history6]
plt.figure(figsize=(13,4.5))

plt.subplot(1,2,1)
for i in range(6):
    if names[i] == 'Baseline':
        plt.plot(histories[i].history['val_loss'], 'k--', linewidth=2.5, label=names[i])
    else:
        plt.plot(histories[i].history['val_loss'], label=names[i])
plt.title('Validation loss semua model')
plt.xlabel('epoch')
plt.ylabel('loss')
plt.legend()

plt.subplot(1,2,2)
for i in range(6):
    if names[i] == 'Baseline':
        plt.plot(histories[i].history['val_acc'], 'k--', linewidth=2.5, label=names[i])
    else:
        plt.plot(histories[i].history['val_acc'], label=names[i])
plt.title('Validation accuracy semua model')
plt.xlabel('epoch')
plt.ylabel('accuracy')
plt.legend()

plt.tight_layout()
plt.show()